@host=http://127.0.0.1:3100
@emailCreditcard=elOrnero32@gmail.com
@apikey=TP2-Secreto

###
GET {{host}}/api/admin/creditCard
Content-Type: application/json

{
    "validacion": "creditCard"
}

###
GET {{host}}/api/apikey/creditCard
x-api-key: {{apikey}}

###
POST {{host}}/user/login
Content-Type: application/json
x-api-key: {{apikey}}

{
    "username": "admin",
    "password": "admin1234"
}

###
GET {{host}}/api/creditCard/{{emailCreditcard}}
x-api-key: {{apikey}}

###
POST {{host}}/api/creditCard
Content-Type: application/json
x-api-key: {{apikey}}

{
  "cardNumber": "789465217581244",
  "cardHolder": "Romeo Ornero",
  "expirationDate": "01/01/2031",
  "cvv": "851",
  "email": "elOrnero32@gmail.com"
}


### 
DELETE {{host}}/api/creditCard/{{emailCreditcard}}
x-api-key: {{apikey}}
    
### 
PATCH {{host}}/api/creditCard/{{emailCreditcard}}
Content-Type: application/json
x-api-key: {{apikey}}

{
    "cardNumber": "8892252311514256",
    "cvv": "884"
}

